use core::fmt;
use std::env;
use std::collections::HashMap;
use std::ffi::os_str::Display;
fn main() {
    let _text_to_ascii_map:HashMap<String,Vec<&str>>=HashMap::from([("A".to_string(),vec![
  " *** ",
  "*   *",
  "*****",
  "*   *",
  "*   *"
]),("B".to_string(),vec!["**** ",
"*   *",
"**** ",
"*   *",
"**** ",
]),("C".to_string(),vec![" ****",
"*    ",
"*    ",
"*    ",
" ****",
]),("D".to_string(),vec!["**** ",
"*   *",
"*   *",
"*   *",
"**** ",
]),("E".to_string(),vec!["*****",
"*    ",
"**** ",
"*    ",
"*****",
]),("F".to_string(),vec!["*****",
"*    ",
"**** ",
"*    ",
"*    ",
]),("G".to_string(),vec![" ****",
"*    ",
"*  **",
"*   *",
" ****",
]),("H".to_string(),vec!["*   *",
"*   *",
"*****",
"*   *",
"*   *",
]),("I".to_string(),vec!["*****",
"  *  ",
"  *  ",
"  *  ",
"*****",
]),("J".to_string(),vec!["*****",
"   * ",
"   * ",
"*  * ",
" **  ",
]),("K".to_string(),vec!["*   *",
"*  * ",
"***  ",
"*  * ",
"*   *",
]),("L".to_string(),vec!["*    ",
"*    ",
"*    ",
"*    ",
"*****",
]),("M".to_string(),vec!["*   *",
"** **",
"* * *",
"*   *",
"*   *",
]),("N".to_string(),vec!["*   *",
"**  *",
"* * *",
"*  **",
"*   *",
]),("O".to_string(),vec![" *** ",
"*   *",
"*   *",
"*   *",
" *** ",
]),("P".to_string(),vec!["**** ",
"*   *",
"**** ",
"*    ",
"*    ",
]),("Q".to_string(),vec![" *** ",
"*   *",
"*   *",
"*  * ",
" ** *",
]),("R".to_string(),vec!["**** ",
"*   *",
"**** ",
"*  * ",
"*   *",
]),("S".to_string(),vec![" ****",
"*    ",
" *** ",
"    *",
"**** ",
]),("T".to_string(),vec!["*****",
"  *  ",
"  *  ",
"  *  ",
"  *  ",
]),("U".to_string(),vec!["*   *",
"*   *",
"*   *",
"*   *",
" *** ",
]),("V".to_string(),vec!["*   *",
"*   *",
"*   *",
" * * ",
"  *  ",
]),("W".to_string(),vec!["*   *",
"*   *",
"* * *",
"** **",
"*   *",
]),("X".to_string(),vec!["*   *",
" * * ",
"  *  ",
" * * ",
"*   *",
]),("Y".to_string(),vec!["*   *",
" * * ",
"  *  ",
"  *  ",
"  *  ",
]),("Z".to_string(),vec!["*****",
"   * ",
"  *  ",
" *   ",
"*****",
]),(" ".to_string(),vec!["     ",
"     ",
"     ",
"     ",
"     ",
])]);

let commands:Vec<String>=env::args().collect();

let word=&commands[1];
let mut counter=0;
while counter<5{
  for c in word.chars(){
  match _text_to_ascii_map.get(&c.to_string()) {
    Some(glyph)=>{
      print!("{}",glyph[counter]);
      print!(" ");
    }
    None=>{
      println!("    ");
    }
}
}
println!("");
 counter+=1;
}
}
